name: Teirraform Deployment

on:
  push:
    paths:
      - "ec2/**"
    branches:
      - main  # Ensure this is the correct branch for deployment
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Initialize Terraform
        run: |
          cd ec2
          terraform init -upgrade

      - name: Terraform Plan
        run: |
          cd ec2
          terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd ec2
          terraform apply -auto-approve tfplan


terraform-destroy:
    needs: terraform-apply
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' # Manually trigger destruction

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Initialize Terraform
        run: |
          cd ec2
          terraform init -upgrade

      - name: Destroy Infrastructure
        run: |
          cd ec2
          terraform destroy -auto-approve



